### ISSUE TITLE
Add a description in readme

### ISSUE THREAD

**Issue by jrichardsz** [ggoral/resource-booking-system#1]
- What does your app? 
- Is a web app?
- Is a rest api?
- What db is used?

Your application looks promising

Thanks

**Comment by ggoral** [comment]
Hi @jrichardsz 

1. App was a college project.
2. No, it isn't.
3. Yes, it is.
4. This app run with MariaDB or MySQL, but is agnostic it would use Postgre.

A fork for this project was used on real scenario.
